In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch import optim
from torch.autograd import Variable
from torch.nn.utils import clip_grad_norm_

In [2]:
from __future__ import unicode_literals, print_function, division

# import basic lib
import re
import math
import random
import string
import unicodedata
import numpy as np
from io import open

# import pytorch
import torch
import torch.nn as nn
import torch.nn.functional as F

from torch import optim
from torch.autograd import Variable
from torch.nn.utils import clip_grad_norm_

# import loss func
import masked_cross_entropy

# check device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [3]:
SOS_idx = 0
EOS_idx = 1
UNK_idx = 2
PAD_idx = 3

USE_CUDA = True

class Preprocessor:
    '''
    class for preprocessing
    '''
    def __init__(self, name):
        '''
        initialize vocab and counter
        '''
        self.name = name
        self.w2idx = {"<sos>" : 0, "<eos>" : 1, "<unk>" : 2, "<pad>" : 3}
        self.counter = {}
        self.idx2w = {0: "<sos>", 1: "<eos>", 2:"<unk>", 3:"<pad>"}
        self.num = 4

    def SentenceAdder(self, sentence):
        '''
        Add a sentence to dataset
        '''
        for word in sentence.split(' '):
            self.WordAdder(word)

    def WordAdder(self, word):
        '''
        Add single word to dataset and update vocab and counter
        '''
        if word in self.w2idx:
            self.counter[word] += 1
        else:
            self.w2idx[word] = self.num
            self.counter[word] = 1
            self.idx2w[self.num] = word
            self.num += 1
            
    def trim(self, min_count=1):
        '''
        Trim to remove non-frequent word
        '''
        keep = []
        for k, v in self.counter.items():
            if v >= min_count: keep.append(k)
        print(self.name+':')
        print('Total words', len(self.w2idx))
        print('After Trimming', len(keep))
        print('Keep Ratio %', 100 * len(keep) / len(self.w2idx))
        self.w2idx = {"<sos>" : 0, "<eos>" : 1, "<unk>" : 2, "<pad>" : 3}
        self.counter = {}
        self.idx2w = {0: "<sos>", 1: "<eos>", 2:"<unk>", 3:"<pad>"}
        self.num = 4
        for w in keep:
            self.WordAdder(w)

In [4]:
def Uni2Ascii(s):
    '''
    transfer from unicode to ascii
    '''
    return ''.join(c for c in unicodedata.normalize('NFD', s)
                    if unicodedata.category(c) != 'Mn')

def StrCleaner(s):
    '''
    trim, delete non-letter and lowercase string
    '''
    s = Uni2Ascii(s.lower().strip())
    s = re.sub(r"([.!?])", r" \1", s)
    s = re.sub(r"[^a-zA-Z.!?]+", r" ", s)
    return s

def DataReader(path, lang1, lang2, reverse=False):
    print("Reading lines...")

    # Read the file and split into lines
    lines = open(path, encoding='utf-8').\
        read().strip().split('\n')

    # Split every line into pairs and normalize
    #pairs = [[StrCleaner(s) for s in l.split('<------>')] for l in lines]
    pairs = [[s.lower() for s in l.split('<------>')] for l in lines]

    # Reverse pairs, make Lang instances
    if reverse:
        pairs = [list(reversed(p)) for p in pairs]
        input_lang = Preprocessor(lang2)
        output_lang = Preprocessor(lang1)
    else:
        input_lang = Preprocessor(lang1)
        output_lang = Preprocessor(lang2)

    return input_lang, output_lang, pairs

In [5]:
MIN_LENGTH = 3
MAX_LENGTH = 50

def filterPair(p):
    '''
    Filter to get expected pairs with specific length
    '''
    return MIN_LENGTH <= len(p[0].split(' ')) <= MAX_LENGTH and \
        MIN_LENGTH <= len(p[1].split(' ')) < MAX_LENGTH

def filterPairs(pairs):
    return [pair for pair in pairs if filterPair(pair)]

In [6]:
def prepareData(path, lang1, lang2, reverse=True):
    input_lang, output_lang, pairs = DataReader(path, lang1, lang2, reverse)
    print("Read %s sentence pairs" % len(pairs))
    pairs = filterPairs(pairs)
    print("Trimmed to %s sentence pairs" % len(pairs))
    print("Counting words...")
    for pair in pairs:
        input_lang.SentenceAdder(pair[0])
        output_lang.SentenceAdder(pair[1])
    print("Counted words:")
    print(input_lang.name, input_lang.num)
    print(output_lang.name, output_lang.num)
    return input_lang, output_lang, pairs


src, tgt, pairs = prepareData('data/train.txt', 'english', 'chinese')
src.trim()
tgt.trim()
print(random.choice(pairs))

Reading lines...
Read 90000 sentence pairs
Trimmed to 77083 sentence pairs
Counting words...
Counted words:
chinese 46064
english 30499
chinese:
Total words 46064
After Trimming 46060
Keep Ratio % 99.99131642931573
english:
Total words 30499
After Trimming 30495
Keep Ratio % 99.9868848158956
['他 说 : 江泽民 总书记 强调 党 的 建设 , 强调 " 三 代表 " 的 思想 , 我 非常 赞赏 .', 'he said he appreciated very much general secretary jiang zemin \'s emphasis on party building and his idea of the " three represents . "']


In [7]:
def sentence2idx(preprocessor, sentence):
    '''
    Read sentence and translate into word index plus eos
    '''
    return [SOS_idx] + [preprocessor.w2idx[w] if w in preprocessor.w2idx \
            else UNK_idx for w in sentence.split(' ')] + [EOS_idx]

def pad(seq, max_len):
    '''
    Add padding to sentence with different length
    '''
    seq += [PAD_idx for i in range(max_len - len(seq))]
    return seq

def random_batch(src, tgt, pairs, batch_size, batch_idx):
    '''
    Randomly generate batch data
    '''
    inputs, target = [], []
    
    # Choose batch
    for s in pairs[batch_idx*batch_size:(batch_idx+1)*batch_size]:
        inputs.append(sentence2idx(src, s[0]))
        target.append(sentence2idx(tgt, s[1]))
        
    # Sort by length
    seq_pairs = sorted(zip(inputs, target), key=lambda p: len(p[0]), reverse=True)
    inputs, target = zip(*seq_pairs)
    
    # Obtain length of each sentence and pad
    input_lens = [len(s) for s in inputs]
    input_max = max(input_lens)
    input_padded = [pad(s, input_max) for s in inputs]
    target_lens = [len(s) for s in target]
    target_max = max(target_lens)
    target_padded = [pad(s, target_max) for s in target]

    # Create Variable
    if USE_CUDA:
        input_vars = Variable(torch.LongTensor(input_padded).cuda()).transpose(0, 1)
        input_lens = Variable(torch.LongTensor(input_lens).cuda())
        target_vars = Variable(torch.LongTensor(target_padded).cuda()).transpose(0, 1)
        target_lens = Variable(torch.LongTensor(target_lens).cuda())
    else:
        input_vars = Variable(torch.LongTensor(input_padded)).transpose(0, 1)
        input_lens = Variable(torch.LongTensor(input_lens))
        target_vars = Variable(torch.LongTensor(target_padded)).transpose(0, 1)
        target_lens = Variable(torch.LongTensor(target_lens))

    return input_vars, input_lens, target_vars, target_lens

In [8]:
class Encoder(nn.Module):
    '''
    Define encoder and forward process
    '''
    def __init__(self, dim_input, dim_embed, dim_hidden, num_layers, dropout):
        super(Encoder, self).__init__()
        self.dim_input = dim_input
        self.dim_hidden = dim_hidden
        self.dim_embed = dim_embed
        self.embed = nn.Embedding(dim_input, dim_embed)
        self.cell = nn.GRU(dim_embed, dim_hidden, 
                          num_layers, dropout=dropout, 
                          bidirectional=True)
        
    def forward(self, inputs, inputs_lens, hidden=None):
        '''
        We need to sum the outputs since bi-diretional is used
        '''
        #print('e')
        embedded = self.embed(inputs)
        packed = nn.utils.rnn.pack_padded_sequence(embedded, inputs_lens)
        outputs, hidden = self.cell(packed, hidden)
        outputs, output_lengths = nn.utils.rnn.pad_packed_sequence(outputs)
        outputs = outputs[:, :, :self.dim_hidden] + \
                    outputs[:, :, self.dim_hidden:]
        return outputs, hidden


class Attention(nn.Module):
    '''
    Define attention mechanism
    '''
    def __init__(self, dim_hidden):
        super(Attention, self).__init__()
        self.dim_hidden = dim_hidden
        # 2*dim_hidden is needed since bi-direction is used
        self.attn = nn.Linear(2*self.dim_hidden, dim_hidden)
        self.v = nn.Parameter(torch.rand(dim_hidden))
        stdv = 1. / math.sqrt(self.v.size(0))
        self.v.data.uniform_(-stdv, stdv)

    def forward(self, hidden, encoder_outputs):
        #print('a')
        timestep = encoder_outputs.size(0)
        h = hidden.repeat(timestep, 1, 1).transpose(0, 1)
        encoder_outputs = encoder_outputs.transpose(0, 1)
        scores = self.score(h, encoder_outputs)
        return F.relu(scores).unsqueeze(1)

    def score(self, hidden, encoder_outputs):
        e = F.softmax(self.attn(torch.cat([hidden, encoder_outputs], 2)),dim=1)
        e = e.transpose(1, 2)
        v = self.v.repeat(encoder_outputs.size(0), 1).unsqueeze(1)
        e = torch.bmm(v, e)
        return e.squeeze(1)


class Decoder(nn.Module):
    '''
    Define decoder with attention
    '''
    def __init__(self, dim_embed, dim_hidden, dim_output, num_layers, dropout):
        super(Decoder, self).__init__()
        self.dim_embed = dim_embed
        self.dim_hidden = dim_hidden
        self.dim_output = dim_output
        self.num_layers = num_layers

        self.embed = nn.Embedding(dim_output, dim_embed)
        self.dropout = nn.Dropout(dropout, inplace=True)
        self.attention = Attention(dim_hidden)
        self.cell = nn.GRU(dim_hidden + dim_embed, dim_hidden,
                          num_layers, dropout=dropout)
        self.out = nn.Linear(2*dim_hidden, dim_output)

    def forward(self, inputs, last_hidden, encoder_outputs):
        
#         print('input size ' + str(inputs.size()))
#         print('input type ' + str(inputs.type()))
        
        embedded = self.embed(inputs).unsqueeze(0)  # (1,B,N)
        embedded = self.dropout(embedded)
        
#         print('emmb size ' + str(embedded.size()))
#         print('emmb type ' + str(embedded.type()))
        
#         input size torch.Size([1])
# input type torch.cuda.LongTensor
# emmb size torch.Size([1, 1, 256])
# emmb type torch.cuda.FloatTensor
        # Calculate attention weights and apply to encoder outputs
        attn_weights = self.attention(last_hidden[-1], encoder_outputs)
        context = attn_weights.bmm(encoder_outputs.transpose(0, 1))  # (B,1,N)
        context = context.transpose(0, 1)  # (1,B,N)
        # Combine embedded input word and attended context, run through RNN

        rnn_input = torch.cat([embedded, context], 2)
        output, hidden = self.cell(rnn_input, last_hidden)
        output = output.squeeze(0)  # (1,B,N) -> (B,N)
        context = context.squeeze(0)
        output = self.out(torch.cat([output, context], 1))
        output = F.log_softmax(output, dim=1)
        return output, hidden, attn_weights

In [9]:
class Seq2Seq(nn.Module):
    def __init__(self, encoder, decoder):
        super(Seq2Seq, self).__init__()
        self.encoder = encoder
        self.decoder = decoder

    def forward(self, src, src_len, tgt, tgt_len, teacher_forcing_ratio=0.5):
        batch_size = src.size(1)
        max_len = tgt.size(0)
        vocab_size = self.decoder.dim_output
        if USE_CUDA:
            outputs = Variable(torch.zeros(max_len, batch_size, vocab_size).cuda())
        else:
            outputs = Variable(torch.zeros(max_len, batch_size, vocab_size))
        encoder_output, hidden = self.encoder(src, src_len)
        hidden = hidden[:self.decoder.num_layers]
        # Put <sos> at first position
        if USE_CUDA:
            output = Variable(tgt.data[0, :].cuda())
        else:
            output = Variable(tgt.data[0, :])
        for t in range(1, max_len):
            output, hidden, attn_weights = self.decoder(
                    output, hidden, encoder_output)
            outputs[t] = output
            # Randomly choose whether to use teacher force or not
            is_teacher = random.random() < teacher_forcing_ratio
            top1 = output.data.max(1)[1]
            if USE_CUDA:
                output = Variable(tgt.data[t].cuda() if is_teacher else top1.cuda())
            else:
                output = Variable(tgt.data[t] if is_teacher else top1)
        return outputs
    
    def inference(self, src, src_len, max_len = MAX_LENGTH):
        pred_idx = []
        batch_size = src.size(1)
        vocab_size = self.decoder.dim_output
        if USE_CUDA:
            outputs = Variable(torch.zeros(max_len, batch_size, vocab_size).cuda())
        else:
            outputs = Variable(torch.zeros(max_len, batch_size, vocab_size))
        
        encoder_output, hidden = self.encoder(src, src_len)
        hidden = hidden[:self.decoder.num_layers]
        # Put <sos> at first position
        if USE_CUDA:
            output = Variable(src.data[0, :].cuda())
        else:
            output = Variable(src.data[0, :])
        pred_idx.append(SOS_idx)
        for t in range(1, max_len):
            output, hidden, attn_weights = self.decoder(
                    output, hidden, encoder_output)
            outputs[t] = output
            top1 = output.data.max(1)[1]
            pred_idx.append(top1.item())
            if USE_CUDA:
                output = Variable(top1.cuda())
            else:
                output = Variable(top1)
            if top1 == EOS_idx: break
        return outputs, pred_idx


In [103]:
batch_size = 128
hidden_size = 512
embed_size = 256
encoder_n_layers = 2
decoder_n_layers = 1 
# n_layers = 4
width = 5
encoder_test = Encoder(src.num, embed_size, hidden_size, encoder_n_layers, dropout=0.2)
decoder_test = Decoder(embed_size, hidden_size, tgt.num, decoder_n_layers, dropout=0.2)

In [104]:
net = Seq2Seq(encoder_test,decoder_test).cuda()
# opt = optim.Adam(net.parameters(),lr=0.0001)
net.load_state_dict(torch.load('./saved_model_1.pt'))


In [105]:
batch_size = 100

test_src, test_tgt, test_pairs = prepareData('data/test.txt', 'english', 'chinese')
test_src.trim()
test_tgt.trim()
print(random.choice(test_pairs))

test_src.w2idx, test_src.idx2w, test_src.num = src.w2idx, src.idx2w, src.num
test_tgt.w2idx, test_tgt.idx2w, test_tgt.num = tgt.w2idx, tgt.idx2w, tgt.num
test_pairs.sort(key=lambda x: len(x[0].split()))

input_batches, input_lengths,\
    target_batches, target_lengths = random_batch(test_src,test_tgt,test_pairs,batch_size,5)

Reading lines...
Read 10000 sentence pairs
Trimmed to 8572 sentence pairs
Counting words...
Counted words:
chinese 17294
english 13049
chinese:
Total words 17294
After Trimming 17290
Keep Ratio % 99.9768705909564
english:
Total words 13049
After Trimming 13045
Keep Ratio % 99.96934631006208
['江泽民 还 谈到 非洲 问题 .', 'jiang zemin also talked about the issue of africa .']


In [151]:
input_batches, input_lengths,\
    target_batches, target_lengths = random_batch(test_src,test_tgt,test_pairs,1,15)

In [153]:
# print(input_batches.size())
# print(target_batches.size())

print(input_batches[:,0])
print(target_batches[:,0])

tensor([  0, 536, 503, 116, 297,   1], device='cuda:0')
tensor([  0, 562,  26,  71, 128, 105,  79, 292, 331,   1], device='cuda:0')


In [206]:
class BeamSearch(nn.Module):
    '''
    Implement BeamSearch for testing
    '''
    
    def __init__(self, encoder, decoder, width):
        super(BeamSearch, self).__init__()
        self.encoder = encoder
        self.decoder = decoder
        self.width = width
        
    def forward(self, src, src_len, width, max_len):
        vocab_size = self.decoder.dim_output        
        encoder_output, hidden = self.encoder(src, src_len)
        hidden = hidden[:self.decoder.num_layers]
        
        if USE_CUDA:
            
            #output is in the shape of batch_size * dict size
            beam_best = Variable(torch.zeros(width, max_len)).cuda()
            prob_best = Variable(torch.zeros(width)).cuda()
            #beam options, all possible width * width options
            beam_options = Variable(torch.zeros(width * width, max_len)).cuda()
            prob_options = Variable(torch.zeros(width * width)).cuda()
            outputs = Variable(torch.zeros(width * width).cuda())
            output = Variable(src.data[0, :].cuda())
            temp = Variable(src.data[0, :].cuda())
            new_output = Variable(src.data[0, :].cuda())
            #index with greatest probablity of size width
            best_output = Variable(torch.zeros(width).cuda())
        else:
            #output is in the shape of batch_size * dict size
            beam_best = Variable(torch.zeros(width, max_len))
            prob_best = Variable(torch.zeros(width))
            #beam options, all possible width * width options
            beam_options = Variable(torch.zeros(width * width, max_len))
            prob_options = Variable(torch.zeros(width * width))
            outputs = Variable(torch.zeros(width * width))
            output = Variable(src.data[0, :])
            new_output = Variable(src.data[0, :])
            #index with greatest probablity of size width
            best_output = Variable(torch.zeros(width))
        
#         print("starting output " + str(output))
#         print("starting output shape " + str(output.size()))
        output, hidden, attn_weights = self.decoder(
            output, hidden, encoder_output)
        
        #val: prob, idx: index
        #fill topk best items
        val, idx = output.data.topk(k = width, dim = 1)
#         print(idx[0,:]) #tensor([  4, 261, 285,  40, 466], device='cuda:0')
#         print(val[0,:]) #tensor([-0.0034, -6.9214, -7.3048, -7.4925, -8.7961], device='cuda:0')
    
        #generate beams
        for i in range(width):
            beam_best[i][1] = idx[0][i]
            prob_best[i] = val[0][i].exp() #since prob log,softmax from -10 to -12
            best_output[i] = idx[0][i]
        
#         print("best output " + str(best_output))
        for t in range(2, max_len):
            cnt = 0
            for i in range(width):
                curr_prob = prob_best[i]
                temp = best_output[i].reshape(1).long()
#                 print("best_output shape " + str(temp.size()))
                new_output, hidden, attn_weights = self.decoder(
                        temp, hidden, encoder_output)
                
                new_output.data = new_output.data.exp() * curr_prob 
                val1, idx1 = new_output.data.topk(k = width, dim = 1)
#                 print('idx1 ' + str(idx1))
#                 print('val1 ' + str(val1))
                
                for j in range(width):
                    beam_options[cnt] = beam_best[i]
#                     print('beam_options_sentence ' + str(beam_options[cnt]))
                    beam_options[cnt][t] = idx1[0][j]
#                     print('word_update ' + str(idx1[0][j]))
#                     print('beam_options_update ' + str(beam_options[cnt]))
                    prob_options[cnt] = val1[0][j]
                    outputs[cnt] = idx1[0][j]
                    cnt += 1
            
#             print('prob_options' + str(prob_options))
            topVal, topInx = prob_options.topk(k = width, dim = 0)
#             print()
#             print('topVal ' + str(topVal))
#             print('topInx ' + str(topInx))
#         
            for j in range(topInx.size(0)):
                prob_best[j] = topVal[j]
                beam_best[j] = beam_options[topInx[j]]  
                best_output[j] = outputs[topInx[j]]
#         print('prob_best ' + str(prob_best))

            
            
        best_index = prob_best.max(0)[1]
#         print('best_inx' + str(best_index))
#         print('beam_option best' + str(beam_options[best_index]))
        return beam_options[best_index].cpu().numpy()

In [196]:
width = 2
net = BeamSearch(net.encoder,net.decoder, width).cuda()


In [197]:
# from utils import bleu
pairs.sort(key=lambda x: len(x[0].split()))

for index_sample in range(2000,2010):
    input_batches, input_lengths,\
        target_batches, target_lengths = random_batch(test_src,test_tgt,pairs,1,index_sample)

    # import bleu
    for test_idx in range(1):
    #     pred = net(input_batches[:,test_idx].reshape(input_lengths[0].item(),1),input_lengths[0].reshape(1), 5)
    #     print("input_batches " + str(input_batches.size()))
    #     print("input_length " + str(input_lengths))
    #     print("target_batches " + str(target_batches.size()))
    #     print("target_lengths " + str(target_lengths))
        pred = net(input_batches[:,test_idx].reshape(input_lengths[0].item(),1), input_lengths[0].reshape(1), width, MAX_LENGTH)

        print('ans' + str(pred))
        inp = ' '.join([src.idx2w[t] for t in input_batches[:,test_idx].cpu().numpy()])
        mt = ' '.join([tgt.idx2w[t] for t in pred if t!= PAD_idx and t!= EOS_idx])
        ref = ' '.join([tgt.idx2w[t] for t in target_batches[:,test_idx].cpu().numpy() if t != PAD_idx])
        print('INPUT:\n' + inp)
        print('REF:\n' + ref)
        print('PREDICTION:\n' + mt)
        #print('BLEU = %f' % bleu([mt],[[ref]],4))
        print("------")


tensor([121,  98], device='cuda:0')
tensor([-0.0072, -4.9540], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  121., 3042., 1721.,   98.,  176., 1472., 7374.,   24.,    1.,
           1.,   24.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
ans[0.000e+00 1.210e+02 3.042e+03 1.721e+03 9.800e+01 1.760e+02 1.472e+03
 7.374e+03 2.400e+01 1.000e+00 1.000e+00 2.400e+01 1.000e+00 1.000e+00
 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
 1.000e+00 1.000e+00 1.00

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,   41.,  213., 1154.,   26.,   46., 1550., 1550.,   24.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
ans[0.000e+00 4.100e+01 2.130e+02 1.154e+03 2.600e+01 4.600e+01 1.550e+03
 1.550e+03 2.400e+01 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
 1.000e+00]
INPUT:
<sos> " 台独 " 是 

In [201]:
import math

def modified_precision(candidate, references, n):
    count = 0
    match_num = 0
    len_c = len(candidate)
    
    for i in range(len_c):
        ref_temp = []
        for reference in references:
            for k in range(len(reference)):
                ref_sentence = reference[k]
                words_ref_sentence = ref_sentence.strip()
                words_ref_sentence = words_ref_sentence.split()
                num_max = len(words_ref_sentence) - n + 1
                ngram_temp = {}
                for j in range(num_max):
                    ngram = ' '.join(words_ref_sentence[j:j+n])
                    ngram = ngram.lower()
                    if ngram in ngram_temp.keys():
                        ngram_temp[ngram] += 1
                    else:
                        ngram_temp[ngram] = 1
                ref_temp.append(ngram_temp)
            
        cand_sentence = candidate[i]
        words_cand = cand_sentence.strip()
        words_cand = words_cand.split()
        num_max_cand = len(words_cand) - n + 1
        cand_temp = {}
        for j in range(num_max_cand):
            ngram = ' '.join(words_cand[j:j+n])
            ngram = ngram.lower()
            if ngram in cand_temp.keys():
                cand_temp[ngram] += 1
            else:
                cand_temp[ngram] = 1
        count += num_max_cand
        match_num += match_counts(ref_temp, cand_temp)
    if match_num != 0:
        p = 1. * match_num / count
    else:
        p = 0
    return p

def match_counts(ref_counts, cand_temp):
    num = 0
    for ngram in cand_temp.keys():
        count = cand_temp[ngram]
        max_ref = 0
        for ref in ref_counts:
            if ngram in ref:
                max_ref = max(max_ref, ref[ngram])
        count = min(max_ref, count)
        num = num + count
    return num

def brevity_penalty(candidate, references):
    len_c = len(candidate)
    r = 0
    c = 0
    for i in range(len_c):
        ref_lens = []
        for reference in references:
            for k in range(len(reference)):
                ref_sentence = reference[k]
                words_ref_sentence = ref_sentence.strip()
                words_ref_sentence = words_ref_sentence.split()
                ref_lens.append(len(words_ref_sentence))
        cand_sentence = candidate[i]
        words_cand = cand_sentence.strip().split()
        init_len_diff = abs(len(words_cand)-ref_lens[0])
        best = ref_lens[0]
        for num in ref_lens:
            if (abs(len(words_cand)-num)) < init_len_diff:
                init_len_diff = abs(len(words_cand) - num)
                best = num
        r = r + best
        c = c + len(words_cand)
    if c > r:
        bp = 1
    else:
        bp = math.exp(1 - 1. * r / c)
    return bp

def bleu(candidate, references, n):
    # n is the maximum length of each ngram you set 
    weight = 1./n
    temp = 0
    for i in range(n):
        p = modified_precision(candidate, references, i + 1)
        temp += math.log(p) * weight if p != 0 else 0
    temp = math.exp(temp)
    return brevity_penalty(candidate, references) * temp

In [207]:
beam_widths = [1,2,3,4,5]
pairs.sort(key=lambda x: len(x[0].split()))
blue_score = []
for i in beam_widths:
#     net = BeamSearch(net.encoder,net.decoder, i).cuda()
    for index_sample in range(2000,2050):
        input_batches, input_lengths,\
            target_batches, target_lengths = random_batch(test_src,test_tgt,pairs,1,index_sample)

        # import bleu
        for test_idx in range(1):
            pred = net(input_batches[:,test_idx].reshape(input_lengths[0].item(),1), input_lengths[0].reshape(1), i, MAX_LENGTH)
    #         print('ans' + str(pred))
            inp = ' '.join([src.idx2w[t] for t in input_batches[:,test_idx].cpu().numpy()])
            mt = ' '.join([tgt.idx2w[t] for t in pred if t!= PAD_idx and t!= EOS_idx])
            ref = ' '.join([tgt.idx2w[t] for t in target_batches[:,test_idx].cpu().numpy() if t != PAD_idx])
    #         print('INPUT:\n' + inp)
    #         print('REF:\n' + ref)
    #         print('PREDICTION:\n' + mt)
            blue_score.append(bleu([mt],[[ref]],4))
    #         print("------")
    
    

tensor([121], device='cuda:0')
tensor([-0.0042], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  121., 3042.,  123.,   98.,  176., 1472., 7374.,   40.,    4.,
         372.,   24.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([25], device='cuda:0')
tensor([-0.6215], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([  0.,  25.,  15., 827.,  15.,  31., 746.,  31.,  31., 746., 416.,  24.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,  24.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,  24.,   1.,   1.,   1.,
          1.,   1.], device='cud

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  827.,   15.,   90.,  418.,  418.,  240., 6006., 6006.,  604.,
          24.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([485], device='cuda:0')
tensor([-0.0106], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  485., 9352., 6861., 9353.,  553.,  833.,  500.,  782.,   24.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
te

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,   46.,  124.,  650., 1166.,   32., 2367.,  118., 2060.,   38.,
         142.,   24.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([1545], device='cuda:0')
tensor([-0.0129], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([    0.,  1545.,    15.,    90.,   227.,  5130., 10106.,  4445.,    24.,
            1.,  4445.,    24.,     1.,     1.,     1.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
            1., 

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,   98.,  909.,  909., 1896.,  328.,  328.,   32., 1810., 1810.,
          24.,    1.,    1.,    1.,   24.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,   24.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([99], device='cuda:0')
tensor([-0.2652], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,   99.,    4.,   79.,  505.,  231.,  555., 1226., 2777.,  331.,
           1., 2777.,  331.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
ten

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  467.,  922.,  922., 1811.,   24.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([142, 116], device='cuda:0')
tensor([-0.3408, -1.7609], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  142.,   26.,   46., 7579., 3472.,  460.,  243.,   24.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       devic

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0., 1374.,   41., 5495.,   41.,   82.,  464.,   24.,   41.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([6747, 1345], device='cuda:0')
tensor([-0.0025, -6.3063], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([    0.,  6747.,  1345., 10010.,    69.,   324.,    24.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
 

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,    4., 2811.,   39.,   26.,    4.,   39.,   24.,    1.,    1.,
          24.,    1.,    1.,   24.,    1.,    1.,   24.,    1.,    1.,    1.,
           1.,    1.,   24.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,   24.,    1.,    1.,   24.,
           1.,    1.,    1.,   24.,    1.,   24.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([422, 689], device='cuda:0')
tensor([-0.0132, -5.6858], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([    0.,   422.,    49.,  5980.,  1411., 10811.,  4519.,  4519.,  4520.,
          395., 10812.,    24.,     1.,  4519.,  4520.,    24.,  4519.,  4520.,
           24.,     1.,  4519.,  4520.,    24.,     1.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
   

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  142.,  810., 3425.,    4.,  633.,   40.,  142.,   24.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([  4,  14, 142], device='cuda:0')
tensor([-0.3187, -1.9758, -2.8858], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,    4., 2441.,   82., 4737.,   24.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.]

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  693.,    4.,  395., 1938.,   24.,   41.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([ 4, 30, 54], device='cuda:0')
tensor([-0.0217, -5.7185, -5.9346], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,    4., 5672., 3865., 3866., 1465., 1465., 1972.,  851.,   24.,
           1., 1465.,   24.,    1., 1465.,   24.,    1.,    1.,    1.,    1.,
        1465.,   24.,    1., 1465.,   24.,    1., 1465.,   24.,    1., 1465.,
          24.,    1.,    1.,    1., 1465.,   24.,    1.,    1.,    1., 1465.,
          24.,    1.,    1.,    1.,    1.,    1.,    1., 1465.,   24.,    1.],
 

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  758.,   15.,   26., 3814.,   24.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([743, 118,  10], device='cuda:0')
tensor([-0.1252, -3.0486, -4.3934], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  743.,    4.,   15.,   26.,   32., 3542.,   24.,   41.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.]

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,    4., 1526., 2564.,   10., 1438., 1439.,   24.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([  4, 225, 425, 226], device='cuda:0')
tensor([-0.0461, -3.6558, -5.6410, -5.7968], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,    4.,  225.,  226.,  271., 2053.,   24.,    1.,   24.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,

best_inxtensor(0, device='cuda:0')
beam_option besttensor([  0., 142.,  82.,  84.,  24.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.], device='cuda:0')
tensor([  30, 1340,  142,    4], device='cuda:0')
tensor([-1.1257, -1.2203, -1.7869, -2.3873], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,   30., 1340., 9460.,  632.,  633.,   24.,    1.,   24.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([ 648,

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0., 1627.,  425.,    4., 1474., 2775.,  118., 3212.,   24.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([   4,   46,  555, 3381], device='cuda:0')
tensor([-0.4341, -1.0584, -6.2783, -7.0192], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,    4., 1016.,   26.,   46.,  675.,   24.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,   

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,   99.,   71.,  231., 1226.,  331.,    1.,  331.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([ 121,   98, 3042,  650,  115], device='cuda:0')
tensor([ -0.0125,  -4.3949,  -9.6158, -11.5872, -13.0434], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  121., 3042., 1472., 7374.,   24.,    1.,    1.,   24.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,  888., 5820.,  511.,   22.,   24.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([ 467, 1181, 1811,  922, 4265], device='cuda:0')
tensor([-0.0272, -4.9360, -5.9269, -6.3615, -6.4740], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([  0., 467., 922.,  24.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
          1.,   1.], device='cuda:0'

best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,   14., 5167., 1663.,   24.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.],
       device='cuda:0')
tensor([1374,  142,   41,   44,   30], device='cuda:0')
tensor([-0.0085, -5.9622, -6.2123, -7.0776, -7.2600], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0., 1374.,   41., 2015., 3476.,   24.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,  

best_inxtensor(0, device='cuda:0')
beam_option besttensor([    0.,    46.,    56.,    46., 10659.,    24.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
            1.,    24.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,     1.,
            1.,     1.,     1.,     1.,     1.], device='cuda:0')
tensor([   4, 2811,  240, 1662,  509], device='cuda:0')
tensor([-0.1264, -2.2087, -5.8157, -6.4734, -6.9394], device='cuda:0')
best_inxtensor(0, device='cuda:0')
beam_option besttensor([   0.,    4., 2811.,  599.,   24.,    1.,   24.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,   24.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,
           1.,    1.,    1.,    1.,    1.,    1.,    1.,    1.,    1., 

In [209]:
print('width=1: ' + str(np.mean(blue_score[:50])))
print('width=2: ' + str(np.mean(blue_score[50:100])))
print('width=3: ' + str(np.mean(blue_score[100:150])))
print('width=4: ' + str(np.mean(blue_score[150:200])))
print('width=5: ' + str(np.mean(blue_score[200:])))

width=1: 0.6401725159577932
width=2: 0.3687788875010727
width=3: 0.27502430825165247
width=4: 0.23007452604541284
width=5: 0.20756734342764677
